/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the RequestAccessTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAccessTokenRequest{}

// RequestAccessTokenRequest struct for RequestAccessTokenRequest
type RequestAccessTokenRequest struct {
	Identity IdentityId `json:"identity"`
}

// NewRequestAccessTokenRequest instantiates a new RequestAccessTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAccessTokenRequest(identity IdentityId) *RequestAccessTokenRequest {
	this := RequestAccessTokenRequest{}
	this.Identity = identity
	return &this
}

// NewRequestAccessTokenRequestWithDefaults instantiates a new RequestAccessTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAccessTokenRequestWithDefaults() *RequestAccessTokenRequest {
	this := RequestAccessTokenRequest{}
	return &this
}

// GetIdentity returns the Identity field value
func (o *RequestAccessTokenRequest) GetIdentity() IdentityId {
	if o == nil {
		var ret IdentityId
		return ret
	}

	return o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value
// and a boolean to check if the value has been set.
func (o *RequestAccessTokenRequest) GetIdentityOk() (*IdentityId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identity, true
}

// SetIdentity sets field value
func (o *RequestAccessTokenRequest) SetIdentity(v IdentityId) {
	o.Identity = v
}

func (o RequestAccessTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAccessTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identity"] = o.Identity
	return toSerialize, nil
}

type NullableRequestAccessTokenRequest struct {
	value *RequestAccessTokenRequest
	isSet bool
}

func (v NullableRequestAccessTokenRequest) Get() *RequestAccessTokenRequest {
	return v.value
}

func (v *NullableRequestAccessTokenRequest) Set(val *RequestAccessTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAccessTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAccessTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAccessTokenRequest(val *RequestAccessTokenRequest) *NullableRequestAccessTokenRequest {
	return &NullableRequestAccessTokenRequest{value: val, isSet: true}
}

func (v NullableRequestAccessTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAccessTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


