/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the SCAFactorStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCAFactorStatus{}

// SCAFactorStatus The state of the factor type. - `PENDING_VERIFICATION` : The user has started the enrolment process but still hasn't completed enrolment. Challenges cannot be used before they are verified. - `ACTIVE` : The user has successfully completed enrolment and the challenge can be used to verify transactions. - `INACTIVE` : The user has rejected the enrolment. 
type SCAFactorStatus struct {
}

// NewSCAFactorStatus instantiates a new SCAFactorStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCAFactorStatus() *SCAFactorStatus {
	this := SCAFactorStatus{}
	return &this
}

// NewSCAFactorStatusWithDefaults instantiates a new SCAFactorStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCAFactorStatusWithDefaults() *SCAFactorStatus {
	this := SCAFactorStatus{}
	return &this
}

func (o SCAFactorStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCAFactorStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableSCAFactorStatus struct {
	value *SCAFactorStatus
	isSet bool
}

func (v NullableSCAFactorStatus) Get() *SCAFactorStatus {
	return v.value
}

func (v *NullableSCAFactorStatus) Set(val *SCAFactorStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSCAFactorStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSCAFactorStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCAFactorStatus(val *SCAFactorStatus) *NullableSCAFactorStatus {
	return &NullableSCAFactorStatus{value: val, isSet: true}
}

func (v NullableSCAFactorStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCAFactorStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


