/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the TransactionId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionId{}

// TransactionId struct for TransactionId
type TransactionId struct {
	Type interface{} `json:"type"`
	Id interface{} `json:"id"`
}

// NewTransactionId instantiates a new TransactionId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionId(type_ interface{}, id interface{}) *TransactionId {
	this := TransactionId{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewTransactionIdWithDefaults instantiates a new TransactionId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionIdWithDefaults() *TransactionId {
	this := TransactionId{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TransactionId) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionId) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TransactionId) SetType(v interface{}) {
	o.Type = v
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TransactionId) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionId) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TransactionId) SetId(v interface{}) {
	o.Id = v
}

func (o TransactionId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableTransactionId struct {
	value *TransactionId
	isSet bool
}

func (v NullableTransactionId) Get() *TransactionId {
	return v.value
}

func (v *NullableTransactionId) Set(val *TransactionId) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionId) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionId(val *TransactionId) *NullableTransactionId {
	return &NullableTransactionId{value: val, isSet: true}
}

func (v NullableTransactionId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


