/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the ManufacturingState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManufacturingState{}

// ManufacturingState Information on the manufacturing of the physical card, as follows:   - REQUESTED: The upgrade of the card to physical has been requested.   - SENT_FOR_FULFILLMENT - The card has been sent for printing.   - DISPATCHED: The card has been manufactured and dispatched.   - DELIVERED: The card has been received and activated by the recipient. 
type ManufacturingState struct {
}

// NewManufacturingState instantiates a new ManufacturingState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManufacturingState() *ManufacturingState {
	this := ManufacturingState{}
	return &this
}

// NewManufacturingStateWithDefaults instantiates a new ManufacturingState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManufacturingStateWithDefaults() *ManufacturingState {
	this := ManufacturingState{}
	return &this
}

func (o ManufacturingState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManufacturingState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableManufacturingState struct {
	value *ManufacturingState
	isSet bool
}

func (v NullableManufacturingState) Get() *ManufacturingState {
	return v.value
}

func (v *NullableManufacturingState) Set(val *ManufacturingState) {
	v.value = val
	v.isSet = true
}

func (v NullableManufacturingState) IsSet() bool {
	return v.isSet
}

func (v *NullableManufacturingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManufacturingState(val *ManufacturingState) *NullableManufacturingState {
	return &NullableManufacturingState{value: val, isSet: true}
}

func (v NullableManufacturingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManufacturingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


