/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the StepupSCAVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StepupSCAVerifyRequest{}

// StepupSCAVerifyRequest struct for StepupSCAVerifyRequest
type StepupSCAVerifyRequest struct {
	// A randomly generated one-time use code.
	VerificationCode interface{} `json:"verificationCode"`
}

// NewStepupSCAVerifyRequest instantiates a new StepupSCAVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStepupSCAVerifyRequest(verificationCode interface{}) *StepupSCAVerifyRequest {
	this := StepupSCAVerifyRequest{}
	this.VerificationCode = verificationCode
	return &this
}

// NewStepupSCAVerifyRequestWithDefaults instantiates a new StepupSCAVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStepupSCAVerifyRequestWithDefaults() *StepupSCAVerifyRequest {
	this := StepupSCAVerifyRequest{}
	return &this
}

// GetVerificationCode returns the VerificationCode field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *StepupSCAVerifyRequest) GetVerificationCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.VerificationCode
}

// GetVerificationCodeOk returns a tuple with the VerificationCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StepupSCAVerifyRequest) GetVerificationCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.VerificationCode) {
		return nil, false
	}
	return &o.VerificationCode, true
}

// SetVerificationCode sets field value
func (o *StepupSCAVerifyRequest) SetVerificationCode(v interface{}) {
	o.VerificationCode = v
}

func (o StepupSCAVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StepupSCAVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.VerificationCode != nil {
		toSerialize["verificationCode"] = o.VerificationCode
	}
	return toSerialize, nil
}

type NullableStepupSCAVerifyRequest struct {
	value *StepupSCAVerifyRequest
	isSet bool
}

func (v NullableStepupSCAVerifyRequest) Get() *StepupSCAVerifyRequest {
	return v.value
}

func (v *NullableStepupSCAVerifyRequest) Set(val *StepupSCAVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStepupSCAVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStepupSCAVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStepupSCAVerifyRequest(val *StepupSCAVerifyRequest) *NullableStepupSCAVerifyRequest {
	return &NullableStepupSCAVerifyRequest{value: val, isSet: true}
}

func (v NullableStepupSCAVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStepupSCAVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


