/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the AuthorisedUserEmailVerificationCodeSend409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorisedUserEmailVerificationCodeSend409Response{}

// AuthorisedUserEmailVerificationCodeSend409Response struct for AuthorisedUserEmailVerificationCodeSend409Response
type AuthorisedUserEmailVerificationCodeSend409Response struct {
	ErrorCode interface{} `json:"errorCode,omitempty"`
}

// NewAuthorisedUserEmailVerificationCodeSend409Response instantiates a new AuthorisedUserEmailVerificationCodeSend409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorisedUserEmailVerificationCodeSend409Response() *AuthorisedUserEmailVerificationCodeSend409Response {
	this := AuthorisedUserEmailVerificationCodeSend409Response{}
	return &this
}

// NewAuthorisedUserEmailVerificationCodeSend409ResponseWithDefaults instantiates a new AuthorisedUserEmailVerificationCodeSend409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorisedUserEmailVerificationCodeSend409ResponseWithDefaults() *AuthorisedUserEmailVerificationCodeSend409Response {
	this := AuthorisedUserEmailVerificationCodeSend409Response{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthorisedUserEmailVerificationCodeSend409Response) GetErrorCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthorisedUserEmailVerificationCodeSend409Response) GetErrorCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return &o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *AuthorisedUserEmailVerificationCodeSend409Response) HasErrorCode() bool {
	if o != nil && IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given interface{} and assigns it to the ErrorCode field.
func (o *AuthorisedUserEmailVerificationCodeSend409Response) SetErrorCode(v interface{}) {
	o.ErrorCode = v
}

func (o AuthorisedUserEmailVerificationCodeSend409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorisedUserEmailVerificationCodeSend409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	return toSerialize, nil
}

type NullableAuthorisedUserEmailVerificationCodeSend409Response struct {
	value *AuthorisedUserEmailVerificationCodeSend409Response
	isSet bool
}

func (v NullableAuthorisedUserEmailVerificationCodeSend409Response) Get() *AuthorisedUserEmailVerificationCodeSend409Response {
	return v.value
}

func (v *NullableAuthorisedUserEmailVerificationCodeSend409Response) Set(val *AuthorisedUserEmailVerificationCodeSend409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorisedUserEmailVerificationCodeSend409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorisedUserEmailVerificationCodeSend409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorisedUserEmailVerificationCodeSend409Response(val *AuthorisedUserEmailVerificationCodeSend409Response) *NullableAuthorisedUserEmailVerificationCodeSend409Response {
	return &NullableAuthorisedUserEmailVerificationCodeSend409Response{value: val, isSet: true}
}

func (v NullableAuthorisedUserEmailVerificationCodeSend409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorisedUserEmailVerificationCodeSend409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


