/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the SCAChannel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCAChannel{}

// SCAChannel - \"SMS\": The one-time-password is sent as a text message - \"AUTHY\": The push notification is sent to an Authy application - \"BIOMETRIC\": The push notification is sent to an innovator application 
type SCAChannel struct {
}

// NewSCAChannel instantiates a new SCAChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCAChannel() *SCAChannel {
	this := SCAChannel{}
	return &this
}

// NewSCAChannelWithDefaults instantiates a new SCAChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCAChannelWithDefaults() *SCAChannel {
	this := SCAChannel{}
	return &this
}

func (o SCAChannel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCAChannel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableSCAChannel struct {
	value *SCAChannel
	isSet bool
}

func (v NullableSCAChannel) Get() *SCAChannel {
	return v.value
}

func (v *NullableSCAChannel) Set(val *SCAChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableSCAChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableSCAChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCAChannel(val *SCAChannel) *NullableSCAChannel {
	return &NullableSCAChannel{value: val, isSet: true}
}

func (v NullableSCAChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCAChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


