/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the SCAChallengeType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCAChallengeType{}

// SCAChallengeType - \"OTP\": The OTP is sent as a text message - \"PUSH\": The authorisation request is sent as a push notification - \"BIOMETRIC\": The push notification is sent via Firebase to a mobile application 
type SCAChallengeType struct {
}

// NewSCAChallengeType instantiates a new SCAChallengeType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCAChallengeType() *SCAChallengeType {
	this := SCAChallengeType{}
	return &this
}

// NewSCAChallengeTypeWithDefaults instantiates a new SCAChallengeType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCAChallengeTypeWithDefaults() *SCAChallengeType {
	this := SCAChallengeType{}
	return &this
}

func (o SCAChallengeType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCAChallengeType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableSCAChallengeType struct {
	value *SCAChallengeType
	isSet bool
}

func (v NullableSCAChallengeType) Get() *SCAChallengeType {
	return v.value
}

func (v *NullableSCAChallengeType) Set(val *SCAChallengeType) {
	v.value = val
	v.isSet = true
}

func (v NullableSCAChallengeType) IsSet() bool {
	return v.isSet
}

func (v *NullableSCAChallengeType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCAChallengeType(val *SCAChallengeType) *NullableSCAChallengeType {
	return &NullableSCAChallengeType{value: val, isSet: true}
}

func (v NullableSCAChallengeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCAChallengeType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


