/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the BlockedReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockedReason{}

// BlockedReason The reason why the instrument has been blocked:   - USER: The root, or an authorised user, of the identity owning the instrument has temporarily blocked the instrument.   - SYSTEM: The platform or an administrator of the platform has temporarily blocked the instrument.   - LOST: The instrument has been blocked because it was marked as lost. 
type BlockedReason struct {
}

// NewBlockedReason instantiates a new BlockedReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockedReason() *BlockedReason {
	this := BlockedReason{}
	return &this
}

// NewBlockedReasonWithDefaults instantiates a new BlockedReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockedReasonWithDefaults() *BlockedReason {
	this := BlockedReason{}
	return &this
}

func (o BlockedReason) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockedReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableBlockedReason struct {
	value *BlockedReason
	isSet bool
}

func (v NullableBlockedReason) Get() *BlockedReason {
	return v.value
}

func (v *NullableBlockedReason) Set(val *BlockedReason) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockedReason) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockedReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockedReason(val *BlockedReason) *NullableBlockedReason {
	return &NullableBlockedReason{value: val, isSet: true}
}

func (v NullableBlockedReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockedReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


