/*
Weavr Multi Product API

Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for your customers.  # Authentication Each request to the Multi API must include an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `auth_token` that represents the user for whom the request is being executed. 

API version: 3.32.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package weavr

import (
	"encoding/json"
)

// checks if the IdentityId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityId{}

// IdentityId struct for IdentityId
type IdentityId struct {
	// Indicates the identity type.
	Type interface{} `json:"type"`
	// The identifier for the identity.
	Id interface{} `json:"id"`
}

// NewIdentityId instantiates a new IdentityId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityId(type_ interface{}, id interface{}) *IdentityId {
	this := IdentityId{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewIdentityIdWithDefaults instantiates a new IdentityId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityIdWithDefaults() *IdentityId {
	this := IdentityId{}
	return &this
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *IdentityId) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityId) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IdentityId) SetType(v interface{}) {
	o.Type = v
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *IdentityId) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityId) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IdentityId) SetId(v interface{}) {
	o.Id = v
}

func (o IdentityId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableIdentityId struct {
	value *IdentityId
	isSet bool
}

func (v NullableIdentityId) Get() *IdentityId {
	return v.value
}

func (v *NullableIdentityId) Set(val *IdentityId) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityId) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityId(val *IdentityId) *NullableIdentityId {
	return &NullableIdentityId{value: val, isSet: true}
}

func (v NullableIdentityId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


